import * as CALLDATA_GAS_COST from '../../calldata-gas-cost';

export const NATIVE_API_URL = 'https://v2.api.native.org/swap-api-v2/v1';

export const NATIVE_ORDERBOOK_POLLING_INTERVAL_MS = 1000;
export const NATIVE_ORDERBOOK_CACHE_TTL_S = 5;

export const NATIVE_GAS_COST =
  CALLDATA_GAS_COST.DEX_OVERHEAD +
  CALLDATA_GAS_COST.ADDRESS * 3 +
  CALLDATA_GAS_COST.AMOUNT * 5 +
  CALLDATA_GAS_COST.FULL_WORD * 4 +
  CALLDATA_GAS_COST.OFFSET_SMALL;

export const NATIVE_FIRM_QUOTE_VERSION = '4';
export const NATIVE_FIRM_QUOTE_EXPIRY_S = 60;
